### ISSUE TITLE
I would like to have the ability to set the lock to false on terraform plan

### ISSUE THREAD

**Issue by VincentPerez** [CircleCI-Public/terraform-orb#105]
**Is your feature request related to a problem? Please describe.**
I would like to have the ability to set the lock to false on terraform plan

**Describe the solution you'd like**
I've written the code to do it [here](https://github.com/CircleCI-Public/terraform-orb/pull/106)

**Describe alternatives you've considered**
I used bash command in my circle ci files, but it's not ideal.

**Comment by marboledacci** [comment]
Thanks for your contribution, the changes are now part of version [3.3.0](https://circleci.com/developer/orbs/orb/circleci/terraform?version=3.3.0)

**Comment by VincentPerez** [comment]
Thanks a lot @marboledacci
