### ISSUE TITLE
Please add "terraform plan --destroy" option

### ISSUE THREAD

**Issue by NikitaForGit** [CircleCI-Public/terraform-orb#113]
Hi,
There are some cases where it would be good to have a `terraform plan -destroy` option to the "plan" (or "destroy") job.
As Terraforms official documentation states : 
"This will run `terraform plan` in **destroy** mode, showing you the proposed destroy changes without executing them."
reference: https://developer.hashicorp.com/terraform/cli/commands/destroy

Its critical to review the changes when it comes to `terraform destroy`

**Comment by marboledacci** [comment]
This is now part of version 3.5
