### ISSUE TITLE
How to pass the Terraform version I need?

### ISSUE THREAD

**Issue by amontalban** [CircleCI-Public/terraform-orb#12]
**Is your feature request related to a problem? Please describe.**
I want to use a specific version of Terraform, looks like the executor allows an `image` parameter to set the Terraform Docker image version but I am not able to change this.

**Describe the solution you'd like**
I would like to define it in my `config.yml` so I can upgrade the Terraform version in a controlled way.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gmemstr** [comment]
@amontalban You can use the `install` command to install a specific version of Terraform: https://circleci.com/developer/orbs/orb/circleci/terraform#commands-install
