### ISSUE TITLE
Ability to override executor (or image)

### ISSUE THREAD

**Issue by dcarley** [CircleCI-Public/terraform-orb#14]
**Is your feature request related to a problem? Please describe.**
The provided executor always uses the latest `hashicorp/terraform:light` image, which can force unexpected upgrades and non-deterministic results between runs. For example CI/CD may work one week on Terraform 0.13 but the job would no longer run the following week due to syntax changes in Terraform 0.14. To override this currently you need to define your own `jobs` to wrap the Orb's `commands` which produces a lot of boilerplate code.

**Describe the solution you'd like**
The ability to pass your own executor to the `jobs`.

**Describe alternatives you've considered**
The [`terraform/default` executor](https://circleci.com/developer/orbs/orb/circleci/node#executors-default) does have an `image` parameter that could be made accessible from the jobs, like the [Node Orb](https://circleci.com/developer/orbs/orb/circleci/node) does. I don't believe you can use a "null" default for a parameter though, so it results in duplicating the default versions across many places in the Orb, which would be harder to maintain. I'd be inclined to remove the executor parameter altogether to make it clearer that it's not usable by the Orb.

**Additional context**
I'll be happy to submit a PR if you can advice which solution you'd prefer.

**Comment by edeesis** [comment]
The upgrade and push of 0.15.0 to `hashicorp/terraform:light` has caused another issue with `init`. I agree that adding the ability to specify your own image as a parameter would be great.

**Comment by KyleTryon** [comment]
This has been resolved in #46
