### ISSUE TITLE
Ability to override execution plan name 

### ISSUE THREAD

**Issue by andormarkus** [CircleCI-Public/terraform-orb#17]
**Is your feature request related to a problem? Please describe.**
In the current implementation the execution plan name is fixed to `plan.out`.  If you CircleCI workflow looks like this [Plan A, Plan B, Plan C] -> HOLD -> [Apply A, Apply B, Apply C] then the parallelly running terraform plan job will be overwrite each others execution plans because they are using the same name. 

**Describe the solution you'd like**
It would be great if this could be moved to a variable and the default value of `plan.out`. It requires small changes in then `plan.yml`. However in the `apply.yml` if you specify non default execution plan name them you have add the name of the plan to execute.

**Additional context**
I'll be happy to submit a PR if you can advice how would you like to implement this in the `apply.yml`

**Comment by orfin-bcg** [comment]
I believe, there's a bigger issue in how "apply" is implemented now.
https://github.com/CircleCI-Public/terraform-orb/blob/master/src/commands/apply.yml#L97

There's currently no way to do the most common pipeline with an independent steps of:  <terraform init> --> <terraform plan> --(manually review the plan)-->  <terraform apply> as current "apply" step:
- already has own terraform init invocation
- does not support passing existing plan file at all.

so generally, current orb's standalone steps of init/plan are useless.

**Comment by dylansmith** [comment]
I agree, the lack of explicit plan support is a non-starter for me.

Edit: Looking at the [source for the `apply` command](https://github.com/CircleCI-Public/terraform-orb/blob/master/src/commands/apply.yml#L100), it appears if you set the environment variable `PLAN_ARGS` ahead of this command and specify the plan location, then it would work.

```sh
terraform apply -auto-approve $PLAN_ARGS "$module_path"
```

**Comment by sl-benoitoyez** [comment]
I just opened a Pull Request which should fix the original issue. 
I also allowed to pass to apply the path to the saved plan. 

PLAN_ARGS did conflict with the module_path as Terraform expect only one or the other but it is now fixed with the -chdir option introduced in 0.14.0.

**Comment by KyleTryon** [comment]
Will be closed by #46 
See comment: https://github.com/CircleCI-Public/terraform-orb/pull/43#issuecomment-885821442
