### ISSUE TITLE
terraform fmt is working only the given directory (or current directory). It should also process subdirectories. (-recursive)

### ISSUE THREAD

**Issue by vinusha-git** [CircleCI-Public/terraform-orb#20]
**Orb Version**
terraform@1.1.1

Using terraform@1.1.1 and looks like terraform fmt is working only the given directory (or current directory). It should also process subdirectories. (-recursive)
Reference: https://www.terraform.io/docs/commands/fmt.html

Current terraform fmt is working only for the given directory. It's not formatting the subdirectories.
teraform fmt -recursive (This command formats subdirectories as well) 
Could please check and fix this.

Terraform documentation:
https://www.terraform.io/docs/commands/fmt.html

Thanks,
Vinusha

**Comment by KyleTryon** [comment]
The "recursive" parameter on the `fmt` job is false by default. This parameter can be set to true.
