### ISSUE TITLE
Support Terraform 0.15.0

### ISSUE THREAD

**Issue by fernfernfern** [CircleCI-Public/terraform-orb#37]
**Is your feature request related to a problem? Please describe.**
Some users would like to start using Terraform 0.15.0, which is not supported by the latest release of the Orb

**Describe the solution you'd like**
The two PRs being worked on should provide users with support for the latest version and features
https://github.com/CircleCI-Public/terraform-orb/pull/33
https://github.com/CircleCI-Public/terraform-orb/pull/35

**Comment by ashraf-revo** [comment]
iam getting this error `Too many command line arguments. Did you mean to use -chdir?
` when upgrade to 0.15.0
any help

**Comment by KyleTryon** [comment]
Resolved in #46. Coming soon.
