### ISSUE TITLE
Include `terraform taint` command

### ISSUE THREAD

**Issue by yaningo** [CircleCI-Public/terraform-orb#39]
**Is your feature request related to a problem? Please describe.**
The `terraform taint` command is not included in the [Terraform orb commands](https://circleci.com/developer/orbs/orb/circleci/terraform#commands) so this functionality is not accessible via the orb.

**Describe the solution you'd like**
Add `taint` to the list of [available commands](https://circleci.com/developer/orbs/orb/circleci/terraform#commands) in the Terraform orb.

**Additional context**
Starting from Terraform v1.0 the [`taint` command is deprecated](https://www.terraform.io/docs/cli/commands/taint.html) however:

- The alternative (create a plan with the "replace" option: `terraform apply -replace=...`) is not available in versions prior to Terraform v1.0
-  The [current Terraform orb `apply` command](https://circleci.com/developer/orbs/orb/circleci/terraform#jobs-apply) doesn't seem to allow options to be passed
- The [orb `install` command](https://circleci.com/developer/orbs/orb/circleci/terraform#commands-install) defaults to Terraform `v0.13.5`
- The default executor uses the `'hashicorp/terraform:0.14.10'` image

**Comment by punkdata** [comment]
@yaningo we're going to look into after the release of PR #46
