### ISSUE TITLE
circleci local execute --job terraform/{fmt,validate,plan,etc} errors with --storage-opt is supported only for overlay over xfs with 'pquota' mount option

### ISSUE THREAD

**Issue by law** [CircleCI-Public/terraform-orb#45]
**Orb Version**
circleci/terraform@2.1.0

**Describe the bug**
Attempting to use the Terraform orb with the circleci-cli utility and trigger a job with `circleci local execute --job terraform/fmt` results in a failed run and the error "Error:   error starting container hashicorp/terraform:0.14.11: Error response from daemon: --storage-opt is supported only for overlay over xfs with 'pquota' mount option"

**To Reproduce**
1. Start with a generic, valid, Terraform repo, the circleci-cli utility 0.1.15410+ba6fe81 (homebrew), and Docker Desktop for Mac v3.5.2
2. Have a basic terraform-orb config like https://gist.github.com/law/507574557a3fe5af31a5d74aa486c11b
3. Try to execute any of the Orb sub-commands like `circleci local execute --job terraform/fmt`
4. Observe the error

**Expected behavior**
`terraform fmt` executes against the Terraform repo

**Comment by punkdata** [comment]
@law thanks for the submission. We'll revisit this after PR #46 is released.

**Comment by marboledacci** [comment]
This seems like a problem on your local, not on the orb. Take a look at [this ](https://support.circleci.com/hc/en-us/articles/7060937560859-How-to-resolve-error-storage-opt-is-supported-only-for-overlay-over-xfs-with-pquota-mount-option-when-running-jobs-locally-with-the-cli)
