### ISSUE TITLE
validate does not include `workspace`

### ISSUE THREAD

**Issue by bushong1** [CircleCI-Public/terraform-orb#55]
**Is your feature request related to a problem? Please describe.**
when using terraform/validate, there's no way to pass terraform.workspace value.

**Describe the solution you'd like**
a parameter on the validate job that accepts the terraform workspace.  We don't use the default workspace, so our modules aren't compatible with this validate task.

**Comment by KyleTryon** [comment]
Terraform Orb 3.1.0 is live: https://github.com/CircleCI-Public/terraform-orb/releases/tag/v3.1.0
Please try the latest version of the orb and let us know what you think!

Version 4.0.0 progress will begin soon with improved support for Terraform cloud and some new sensible defaults.
