### ISSUE TITLE
apply does not seem to read in plan file

### ISSUE THREAD

**Issue by naseemkullah** [CircleCI-Public/terraform-orb#63]
The [usage examples](https://circleci.com/developer/orbs/orb/circleci/terraform) seem to suggest that the plan file is passed through via attaching a workspace between plan and apply jobs but I don't see how it works:

https://github.com/CircleCI-Public/terraform-orb/blob/0d0e0587128d868e0f10443b35d0381db358ae9c/src/scripts/apply.sh#L66

does not read in the plan file (plan.out)  from https://github.com/CircleCI-Public/terraform-orb/blob/0d0e0587128d868e0f10443b35d0381db358ae9c/src/scripts/plan.sh#L69

**Comment by KyleTryon** [comment]
Hello @naseemkullah.
I have opened a PR #74 which should have a backwards compatible change. If you are able, I'd love your feedback. The orb can also be tested here:

> You can preview what this will look like on the CircleCI Orb Registry at the following link: 
> https://circleci.com/developer/orbs/orb/circleci/terraform?version=dev:0cadaa0d00d2b4b54dd67f498057802e9c327329

**Comment by KyleTryon** [comment]
Terraform Orb 3.1.0 is live: https://github.com/CircleCI-Public/terraform-orb/releases/tag/v3.1.0
Please try the latest version of the orb and let us know what you think!

Version 4.0.0 progress will begin soon with improved support for Terraform cloud and some new sensible defaults.
