### ISSUE TITLE
Add the ability to specify the lock timeout on terraform plan and apply

### ISSUE THREAD

**Issue by mark-russell-bossanova** [CircleCI-Public/terraform-orb#82]
**Is your feature request related to a problem? Please describe.**
I have my terraform state files on Google. I have run into situations where some one is running a terraform apply on their desk and CircleCi is running a build.  This causes a build failure because CircleCi can not get the terraform remote lock. The default amount of wait time to get the lock is `0s`.

**Describe the solution you'd like**
 I would like to be able to add a `-lock-timeout=sometimeout` or pass a lock timeout to the parameter to terraform commands/jobs `plan` and `apply`.  This way I would be able to have terraform wait for a specified amount of time to get the lock.  This would avoid build failures in most cases.

**Describe alternatives you've considered**
I have looked through the code and since this has to be a command line parameter I see no way to pass it to the orb to add the parameter to terraform command

**Additional context**
With some guidance I will be willing to make a pull request for this.

**Comment by mark-russell-bossanova** [comment]
I will work this in to my next quarter's Goals.

**Comment by marboledacci** [comment]
Looks like this was added a while ago on #92
