### ISSUE TITLE
git lfs failed when using the terraform orb due to no image or something?

### ISSUE THREAD

**Issue by deantray** [CircleCI-Public/terraform-orb#86]
3.1.0

Many repos use "git lfs" for large files.  We also use AWS tools for other things in our deploy job which would like to do terraform(We are trialing it with a wire into CI of the next 4 weeks but that didn't work out well so we can't start using it).  The orb has an executor and not an image which is weird.  Is there another way(a terraform image with AWS tools) we can use.

git lfs install failed so not all files are there in the checkout(and this failed the build as well) ->

#!/bin/sh -eo pipefail
sudo apt-get update && sudo apt-get install git-lfs; git lfs install
/bin/sh: sudo: not found
git: 'lfs' is not a git command. See 'git --help'.

The most similar command is
	log

Exited with code exit status 1
CircleCI received exit code 1

**Comment by marboledacci** [comment]
The executor uses the official terraform image by Hashicorp https://hub.docker.com/r/hashicorp/terraform.
We don't provide any image with the specifications you mentioned, but you can use any docker image you want.
About your error, the terraform image from hashicorp uses root user therefore there is no sudo command, just use the command without sudo.
