### ISSUE TITLE
Terraform init is missing the -upgrade flag

### ISSUE THREAD

**Issue by fleetwoodstack** [CircleCI-Public/terraform-orb#90]
**Is your feature request related to a problem? Please describe.**
Whenever providers in a terraform project change (e.g. version upgrades), we need to run 'terraform init -upgrade'. However the terraform init doesn't pass this -upgrade flag in by default.

**Describe the solution you'd like**
By default, we should be passing in the -upgrade flag to terraform init. This way, any provider changes naturally get upgraded as versions need to change.

**Describe alternatives you've considered**
An alternative is you could have a separate parameter for users to pass in any flags they want, bypassing the need for feature requests for additional parameters.

**Additional context**
Add any other context about the feature request here.

**Comment by marboledacci** [comment]
The init command now has the option to have the -upgrade flag on the init command, version [3.3.0](https://circleci.com/developer/orbs/orb/circleci/terraform?version=3.3.0)
