### ISSUE TITLE
publishing failing pls suggest

### ISSUE THREAD

**Issue by gopuc365** [CircleCI-Public/terraform-orb#99]
Hello i get this error. pls help
Preparing to publish your orb.
No Orb Publishing Token detected.
Please set the ORB_PARAM_ORB_PUB_TOKEN environment variable.
Aborting deployment.
Exited with code exit status 1
how to assign token? is that public cloud credential

**Comment by marboledacci** [comment]
What are you doing to get this error? This doesn't seem related to the terraform-orb.
